name: Ensure Tag Matches alire.toml Version

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  ensure-tag-matches-alire-toml-version:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: block
          disable-sudo: true
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            pypi.org:443
            files.pythonhosted.org:443

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
        with:
          cache: pip
          cache-dependency-path: .github/workflows/requirements.txt

      - name: Install dependencies
        run: pip install --require-hashes -r requirements-ensure-tags-match-alire-toml-version.txt

      - name: Verify tag matches version
        run: python hooks/ensure_tag_matches_alire_toml_version.py
